config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :charts
  resources :profits
  root to:  'pages#home'

  resources :yr_profits
  resources :qt_profits
  resources :epss
  resources :stocks
  resources :tickers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get "/list_epss", to: 'epss#list_epss'    
    get "/display", to: 'tickers#display'        

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
class Chart < ApplicationRecord
	belongs_to :ticker
	before_save :assign_names
	default_scope { order(name: 'asc') }

  	YEAR = [
          	"2018",
          	"2017",
						"2016",
						"2015",
						"2014",
						"2013",
						"2012",
						"2011"
        	]

  	QUARTER = [
          	"4",
          	"3",
          	"2",
            "1"
        	]

private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name
  	end

end

app/models/consensu.rb
class Consensu < ApplicationRecord
  belongs_to :ticker
end

app/models/eps.rb
class Eps < ApplicationRecord

	belongs_to :ticker
	before_save :assign_names
 #  default_scope { order(name: 'asc', year: 'desc', quarter: 'desc') }

  	YEAR = [
			"2024", 			
			"2023", 			
			"2022", 			
			"2021",
			"2020",
      "2019",
      "2018",
      "2017",
			"2016",
			"2015",
			"2014"
        	]

  	QUARTER = [
			"3",
			"2",
			"1",
			"4"
		]

	def q_amt_in_million
     	q_amt.div(1000)
   	end

  	def y_amt_in_million
     	y_amt.div(1000)
   	end

  	def aq_amt_in_million
     	aq_amt.div(1000)
   	end

  	def ay_amt_in_million
     	ay_amt.div(1000)
   	end

	private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name

    	if (self.quarter == 4)
       		eps = Eps.where(name: self.name, year: self.year, quarter: '3')
        	if eps
          		self.q_amt = self.aq_amt - eps.first.aq_amt
          		self.y_amt = self.ay_amt - eps.first.ay_amt
          		self.q_eps = self.aq_eps - eps.first.aq_eps
          		self.y_eps = self.ay_eps - eps.first.ay_eps
        	end
    	end

    	if (self.quarter == 1)
          	self.aq_amt  = self.q_amt
          	self.ay_amt  = self.y_amt
          	self.aq_eps  = self.q_eps
          	self.ay_eps  = self.y_eps
    	end

  	end

end

app/models/exempt.rb
class Exempt < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :ticker
  #validates :name, :uniqueness => true
	before_save :assign_names
 #  default_scope { order(name: 'asc', year: 'desc', quarter: 'desc') }

  YEAR = [
          "2020",
			    "2019"
        	]

  QUARTER = [
            "2",
            "1",      
            "4",
          	"3"
    ]
    
    HOUR = [
      "23",      
      "22",
      "21",
      "20",      
      "19",
      "18",
      "17",
      "13",
      "12",      
      "09",
      "08",
      "07",
      "06"
]    

	private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name
  end

end

app/models/profit.rb
class Profit < ApplicationRecord
  belongs_to :ticker
end

app/models/qt_profit.rb
class QtProfit < ApplicationRecord
  belongs_to :ticker
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :ticker
end

app/models/ticker.rb
class Ticker < ApplicationRecord
	has_one :stock, dependent: :destroy
	has_one :consensu, dependent: :destroy

	has_many :epss, dependent: :destroy
	has_many :charts, dependent: :destroy	
	has_many :tmp_epss, dependent: :destroy	
	has_many :qt_profits, dependent: :destroy
	has_many :yr_profits, dependent: :destroy
    default_scope { order(name: 'asc') }
end

app/models/tmp_eps.rb
class TmpEps < ApplicationRecord
  belongs_to :ticker
end

app/models/yr_dividend.rb
class YrDividend < ApplicationRecord
  belongs_to :ticker
end

app/models/yr_profit.rb
class YrProfit < ApplicationRecord
  belongs_to :ticker
end

app/controllers/yr_profits_controller.rb
class YrProfitsController < ApplicationController
  before_action :set_yr_profit, only: [:show, :edit, :update, :destroy]

  # GET /yr_profits
  # GET /yr_profits.json
  def index
    @yr_profits = YrProfit.all
  end

  # GET /yr_profits/1
  # GET /yr_profits/1.json
  def show
  end

  # GET /yr_profits/new
  def new
    @yr_profit = YrProfit.new
  end

  # GET /yr_profits/1/edit
  def edit
  end

  # POST /yr_profits
  # POST /yr_profits.json
  def create
    @yr_profit = YrProfit.new(yr_profit_params)

    respond_to do |format|
      if @yr_profit.save
        format.html { redirect_to @yr_profit, notice: 'Yr profit was successfully created.' }
        format.json { render :show, status: :created, location: @yr_profit }
      else
        format.html { render :new }
        format.json { render json: @yr_profit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yr_profits/1
  # PATCH/PUT /yr_profits/1.json
  def update
    respond_to do |format|
      if @yr_profit.update(yr_profit_params)
        format.html { redirect_to @yr_profit, notice: 'Yr profit was successfully updated.' }
        format.json { render :show, status: :ok, location: @yr_profit }
      else
        format.html { render :edit }
        format.json { render json: @yr_profit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yr_profits/1
  # DELETE /yr_profits/1.json
  def destroy
    @yr_profit.destroy
    respond_to do |format|
      format.html { redirect_to yr_profits_url, notice: 'Yr profit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yr_profit
      @yr_profit = YrProfit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yr_profit_params
      params.require(:yr_profit).permit(:name, :year, :quarter, :latest_amt, :previous_amt, :inc_amt, :inc_pct)
    end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/epss_helper.rb
module EpssHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profits_helper.rb
module ProfitsHelper
end

app/helpers/qt_profits_helper.rb
module QtProfitsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/helpers/yr_profits_helper.rb
module YrProfitsHelper
end

app/views/yr_profits/_form.html.erb
<%= form_with(model: yr_profit, local: true) do |form| %>
  <% if yr_profit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(yr_profit.errors.count, "error") %> prohibited this yr_profit from being saved:</h2>

      <ul>
      <% yr_profit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :yr_profit_name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :yr_profit_year %>
  </div>

  <div class="field">
    <%= form.label :quarter %>
    <%= form.text_field :quarter, id: :yr_profit_quarter %>
  </div>

  <div class="field">
    <%= form.label :latest_amt %>
    <%= form.text_field :latest_amt, id: :yr_profit_latest_amt %>
  </div>

  <div class="field">
    <%= form.label :previous_amt %>
    <%= form.text_field :previous_amt, id: :yr_profit_previous_amt %>
  </div>

  <div class="field">
    <%= form.label :inc_amt %>
    <%= form.text_field :inc_amt, id: :yr_profit_inc_amt %>
  </div>

  <div class="field">
    <%= form.label :inc_pct %>
    <%= form.text_field :inc_pct, id: :yr_profit_inc_pct %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/yr_profits/edit.html.erb
<h1>Editing Yr Profit</h1>

<%= render 'form', yr_profit: @yr_profit %>

<%= link_to 'Show', @yr_profit %> |
<%= link_to 'Back', yr_profits_path %>

app/views/yr_profits/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Yearly Profits</h2>

<table id="yr_profits" class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Year</th>      
            <th>Qtr</th>
            <th>Profit Up</th>
            <th>Up Pct</th>
            <th>Price</th>    
            <th>Max</th> 
            <th>Pct</th>  
            <th>Target</th>  
            <th>B</th>
            <th>H</th>        
            <th>S</th>               
            <th>P/E</th>
            <th>P/BV</th>        
            <th>Volume</th>
            <th>Beta</th>           
            <th></th>
            <th></th>      
        </tr>
    </thead>

    <tbody>
        <% @yr_profits.each do |yr_profit| %>
            <tr>
                <td><%= yr_profit.name %></td>
                <td><%= yr_profit.year %></td>
                <td><%= yr_profit.quarter %></td>
                <td><%= number_with_precision(yr_profit.inc_amt, precision: 0, delimiter: ',') %></td>
                <td><%= number_with_precision(yr_profit.inc_pct, precision: 1, delimiter: ',') %></td>
                <td><%= number_with_precision(yr_profit.ticker.stock.price, precision: 2) %></td>
                <td><%= number_with_precision(yr_profit.ticker.stock.max_price, precision: 2) %></td>   
                <td><%= number_with_precision((yr_profit.ticker.stock.max_price-yr_profit.ticker.stock.price)/
                yr_profit.ticker.stock.price*100, precision: 2) %></td>   
                <% consensu = Consensu.find_by_name(yr_profit.name) %>

                <% if consensu %> 
                  <td><%= number_with_precision(consensu.target_price, precision: 2) %></td>  
                  <td><%= consensu.buy %></td>  
                  <td><%= consensu.hold %></td> 
                  <td><%= consensu.sell %></td> 
                <% else %>
                  <td><%= 0.00 %></td>
                  <td><%= 0 %></td>  
                  <td><%= 0 %></td>
                  <td><%= 0 %></td>                            
                <% end %>

                <td><%= number_with_precision(yr_profit.ticker.stock.pe, precision: 2) %></td>
                <td><%= number_with_precision(yr_profit.ticker.stock.pbv, precision: 2) %></td>         
                <td><%= number_with_precision(yr_profit.ticker.stock.daily_volume, precision: 2, delimiter: ',') %></td>
                <td><%= number_with_precision(yr_profit.ticker.stock.beta, precision: 2) %></td>              
                <td><%= link_to 'S', yr_profit %></td>
                <td><%= link_to 'D', yr_profit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Profit', new_yr_profit_path %>

app/views/yr_profits/new.html.erb
<h1>New Yr Profit</h1>

<%= render 'form', yr_profit: @yr_profit %>

<%= link_to 'Back', yr_profits_path %>

app/views/yr_profits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yr_profit.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @yr_profit.year %>
</p>

<p>
  <strong>Quarter:</strong>
  <%= @yr_profit.quarter %>
</p>

<p>
  <strong>Latest amt:</strong>
  <%= @yr_profit.latest_amt %>
</p>

<p>
  <strong>Previous amt:</strong>
  <%= @yr_profit.previous_amt %>
</p>

<p>
  <strong>Inc amt:</strong>
  <%= @yr_profit.inc_amt %>
</p>

<p>
  <strong>Inc pct:</strong>
  <%= @yr_profit.inc_pct %>
</p>

<%= link_to 'Edit', edit_yr_profit_path(@yr_profit) %> |
<%= link_to 'Back', yr_profits_path %>