config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :charts
  resources :profits
  root to:  'pages#home'

  resources :yr_profits
  resources :qt_profits
  resources :epss
  resources :stocks
  resources :tickers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get "/list_epss", to: 'epss#list_epss'    
    get "/display", to: 'tickers#display'        

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
class Chart < ApplicationRecord
	belongs_to :ticker
	before_save :assign_names
	default_scope { order(name: 'asc') }

  	YEAR = [
          	"2018",
          	"2017",
						"2016",
						"2015",
						"2014",
						"2013",
						"2012",
						"2011"
        	]

  	QUARTER = [
          	"4",
          	"3",
          	"2",
            "1"
        	]

private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name
  	end

end

app/models/consensu.rb
class Consensu < ApplicationRecord
  belongs_to :ticker
end

app/models/eps.rb
class Eps < ApplicationRecord

	belongs_to :ticker
	before_save :assign_names
 #  default_scope { order(name: 'asc', year: 'desc', quarter: 'desc') }

  	YEAR = [
			"2024", 			
			"2023", 			
			"2022", 			
			"2021",
			"2020",
      "2019",
      "2018",
      "2017",
			"2016",
			"2015",
			"2014"
        	]

  	QUARTER = [
			"3",
			"2",
			"1",
			"4"
		]

	def q_amt_in_million
     	q_amt.div(1000)
   	end

  	def y_amt_in_million
     	y_amt.div(1000)
   	end

  	def aq_amt_in_million
     	aq_amt.div(1000)
   	end

  	def ay_amt_in_million
     	ay_amt.div(1000)
   	end

	private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name

    	if (self.quarter == 4)
       		eps = Eps.where(name: self.name, year: self.year, quarter: '3')
        	if eps
          		self.q_amt = self.aq_amt - eps.first.aq_amt
          		self.y_amt = self.ay_amt - eps.first.ay_amt
          		self.q_eps = self.aq_eps - eps.first.aq_eps
          		self.y_eps = self.ay_eps - eps.first.ay_eps
        	end
    	end

    	if (self.quarter == 1)
          	self.aq_amt  = self.q_amt
          	self.ay_amt  = self.y_amt
          	self.aq_eps  = self.q_eps
          	self.ay_eps  = self.y_eps
    	end

  	end

end

app/models/exempt.rb
class Exempt < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :ticker
  #validates :name, :uniqueness => true
	before_save :assign_names
 #  default_scope { order(name: 'asc', year: 'desc', quarter: 'desc') }

  YEAR = [
          "2020",
			    "2019"
        	]

  QUARTER = [
            "2",
            "1",      
            "4",
          	"3"
    ]
    
    HOUR = [
      "23",      
      "22",
      "21",
      "20",      
      "19",
      "18",
      "17",
      "13",
      "12",      
      "09",
      "08",
      "07",
      "06"
]    

	private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name
  end

end

app/models/profit.rb
class Profit < ApplicationRecord
  belongs_to :ticker
end

app/models/qt_profit.rb
class QtProfit < ApplicationRecord
  belongs_to :ticker
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :ticker
end

app/models/ticker.rb
class Ticker < ApplicationRecord
	has_one :stock, dependent: :destroy
	has_one :consensu, dependent: :destroy

	has_many :epss, dependent: :destroy
	has_many :charts, dependent: :destroy	
	has_many :tmp_epss, dependent: :destroy	
	has_many :qt_profits, dependent: :destroy
	has_many :yr_profits, dependent: :destroy
    default_scope { order(name: 'asc') }
end

app/models/tmp_eps.rb
class TmpEps < ApplicationRecord
  belongs_to :ticker
end

app/models/yr_dividend.rb
class YrDividend < ApplicationRecord
  belongs_to :ticker
end

app/models/yr_profit.rb
class YrProfit < ApplicationRecord
  belongs_to :ticker
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :hour, :publish_date, :quarter, :year, :ticker_id)
    end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/epss_helper.rb
module EpssHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profits_helper.rb
module ProfitsHelper
end

app/helpers/qt_profits_helper.rb
module QtProfitsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/helpers/yr_profits_helper.rb
module YrProfitsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <!-- row 1 -->
    <div class="row">
        <div class="col-xs-6">
            <label class="control-label col-sm-6"><%= f.label :ticker_id %></label>
            <%= f.collection_select :ticker_id, Ticker.all, :id, :name %>
        </div>

        <div class="col-xs-6">
            <label class="control-label col-sm-6"><%= 'Action' %></label>
            <%= f.submit %>
        </div>
    </div>
    <!-- row 3 -->
    <div class="row">
        <div class="col-xs-6">
            <label class="control-label col-sm-6"><%= f.label :hour %>
              <%= f.select :hour, Item::HOUR, {} %>
        </div>
        <div class="col-xs-6">
            <label class="control-label col-sm-6"><%= f.label :publish_date %></label>
            <%= f.date_select :publish_date, :start_year => 2018, :end_year => 2020,
    order: [:day, :month, :year]  %>
        </div>
    </div>
    <!-- row 4 -->
    <div class="row">
        <div class="col-xs-6">
            <label class="control-label col-sm-6"><%= f.label :quarter %></label>
            <%= f.select :quarter, Item::QUARTER, {} %>
        </div>
        <div class="col-xs-6">
            <label class="control-label col-sm-6"><%= f.label :year %></label>
            <%= f.select :year, Item::YEAR, {} %>
        </div>
    </div>

<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>
<table id="items" class="display table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Market</th>
      <th>Sector</th>
      <th>Subsector</th>
      <th>Hour</th>
      <th>Publish date</th>
      <th>Quarter</th>
      <th>Year</th>
      <th>E</th>
      <th>D</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
    <% if item.ticker.market != 'mai' %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.ticker.market %></td>
        <td><%= item.ticker.sector %></td>
        <td><%= item.ticker.subsector %></td>
        <td><%= item.hour %></td>
        <td><%= item.publish_date %></td>
        <td><%= item.quarter %></td>
        <td><%= item.year %></td>
        <td><%= link_to 'E', edit_item_path(item), target: "_new" %></td>
        <td><%= link_to 'D', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @item.hour %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @item.publish_date %>
</p>

<p>
  <strong>Quarter:</strong>
  <%= @item.quarter %>
</p>

<p>
  <strong>Year:</strong>
  <%= @item.year %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>