config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :charts
  resources :profits
  root to:  'pages#home'

  resources :yr_profits
  resources :qt_profits
  resources :epss
  resources :stocks
  resources :tickers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get "/list_epss", to: 'epss#list_epss'    
    get "/display", to: 'tickers#display'        

end

app/models/chart.rb
class Chart < ApplicationRecord
	belongs_to :ticker
	before_save :assign_names
	default_scope { order(name: 'asc') }

  	YEAR = [
          	"2018",
          	"2017",
						"2016",
						"2015",
						"2014",
						"2013",
						"2012",
						"2011"
        	]

  	QUARTER = [
          	"4",
          	"3",
          	"2",
            "1"
        	]

private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name
  	end

end

app/models/consensu.rb
class Consensu < ApplicationRecord
  belongs_to :ticker
end

app/models/eps.rb
class Eps < ApplicationRecord

	belongs_to :ticker
	before_save :assign_names
 #  default_scope { order(name: 'asc', year: 'desc', quarter: 'desc') }

  	YEAR = [
			"2024", 			
			"2023", 			
			"2022", 			
			"2021",
			"2020",
      "2019",
      "2018",
      "2017",
			"2016",
			"2015",
			"2014"
        	]

  	QUARTER = [
			"3",
			"2",
			"1",
			"4"
		]

	def q_amt_in_million
     	q_amt.div(1000)
   	end

  	def y_amt_in_million
     	y_amt.div(1000)
   	end

  	def aq_amt_in_million
     	aq_amt.div(1000)
   	end

  	def ay_amt_in_million
     	ay_amt.div(1000)
   	end

	private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name

    	if (self.quarter == 4)
       		eps = Eps.where(name: self.name, year: self.year, quarter: '3')
        	if eps
          		self.q_amt = self.aq_amt - eps.first.aq_amt
          		self.y_amt = self.ay_amt - eps.first.ay_amt
          		self.q_eps = self.aq_eps - eps.first.aq_eps
          		self.y_eps = self.ay_eps - eps.first.ay_eps
        	end
    	end

    	if (self.quarter == 1)
          	self.aq_amt  = self.q_amt
          	self.ay_amt  = self.y_amt
          	self.aq_eps  = self.q_eps
          	self.ay_eps  = self.y_eps
    	end

  	end

end

app/models/exempt.rb
class Exempt < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :ticker
  #validates :name, :uniqueness => true
	before_save :assign_names
 #  default_scope { order(name: 'asc', year: 'desc', quarter: 'desc') }

  YEAR = [
          "2020",
			    "2019"
        	]

  QUARTER = [
            "2",
            "1",      
            "4",
          	"3"
    ]
    
    HOUR = [
      "23",      
      "22",
      "21",
      "20",      
      "19",
      "18",
      "17",
      "13",
      "12",      
      "09",
      "08",
      "07",
      "06"
]    

	private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name
  end

end

app/models/profit.rb
class Profit < ApplicationRecord
  belongs_to :ticker
end

app/models/qt_profit.rb
class QtProfit < ApplicationRecord
  belongs_to :ticker
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :ticker
end

app/models/ticker.rb
class Ticker < ApplicationRecord
	has_one :stock, dependent: :destroy
	has_one :consensu, dependent: :destroy

	has_many :epss, dependent: :destroy
	has_many :charts, dependent: :destroy	
	has_many :tmp_epss, dependent: :destroy	
	has_many :qt_profits, dependent: :destroy
	has_many :yr_profits, dependent: :destroy
    default_scope { order(name: 'asc') }
end

app/models/tmp_eps.rb
class TmpEps < ApplicationRecord
  belongs_to :ticker
end

app/models/yr_dividend.rb
class YrDividend < ApplicationRecord
  belongs_to :ticker
end

app/models/yr_profit.rb
class YrProfit < ApplicationRecord
  belongs_to :ticker
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/epss_helper.rb
module EpssHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profits_helper.rb
module ProfitsHelper
end

app/helpers/qt_profits_helper.rb
module QtProfitsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><% if content_for?(:title) %><%= yield :title %><% else %>PortLt<% end %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

    <body class="<%= controller.controller_name %>">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="#" class="navbar-brand">PortLt</a>
        </div> <!--end navbar-header -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'List', list_epss_path %></li>            
            <li><%= link_to 'EPS', epss_path %></li>            
            <li><%= link_to 'Qt Profits', qt_profits_path %></li>   
            <li><%= link_to 'Yr Profits', yr_profits_path %></li>  
            <li><%= link_to 'Profits', profits_path %></li>                       
            <li><%= link_to 'Stocks', stocks_path %></li>
            <li><%= link_to 'Tickers', tickers_path %></li>  
            <li><%= link_to 'Charts', charts_path %></li>                        
          </ul>
          
        </div><!--end of collapse navbar-collapse -->

      </div> <!-- end of container -->
    </nav>  <!-- End of nav element --> 
    <div class="container bodyContent">
     <!-- from Bootstrap for Rails -->
      <%= yield %>
    </div> <!-- end of container -->

  </body>
</html>

app/views/pages/home.html.erb
<div class ="page-header text-center" > 
  <h1>Home</h1>
</div>